/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CompletedLesson { 'lessonId' : string, 'completedAt' : bigint }
export interface HttpHeader { 'value' : string, 'name' : string }
export interface HttpResponse {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<HttpHeader>,
}
export interface HttpTransformArgs {
  'context' : Uint8Array,
  'response' : HttpResponse,
}
export interface QA { 'at' : Time, 'question' : string, 'response' : string }
export type Time = bigint;
export type TokenExchangeResult = { 'ok' : string } |
  { 'err' : string };
export interface TokenStatus {
  'isExpired' : boolean,
  'hasRefreshToken' : boolean,
  'hasToken' : boolean,
}
export type TweetResult = { 'ok' : string } |
  { 'err' : string };
export interface _SERVICE {
  'askQuestion' : ActorMethod<
    [[] | [string], [] | [string], string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'disconnectX' : ActorMethod<[], undefined>,
  'exchangeToken' : ActorMethod<[string, string, string], TokenExchangeResult>,
  /**
   * / Get the global X (Twitter) OAuth 2.0 Client ID.
   */
  'getClientId' : ActorMethod<[], [] | [string]>,
  'getOpenAIKey' : ActorMethod<[], [] | [string]>,
  'getProgress' : ActorMethod<[], Array<CompletedLesson>>,
  'getQAHistory' : ActorMethod<[[] | [string]], Array<QA>>,
  'getTokenStatus' : ActorMethod<[], TokenStatus>,
  'markComplete' : ActorMethod<[string], undefined>,
  'postTweet' : ActorMethod<[string, string], TweetResult>,
  'resetProgress' : ActorMethod<[], undefined>,
  /**
   * / Set the global X (Twitter) OAuth 2.0 Client ID.
   */
  'setClientId' : ActorMethod<[string], undefined>,
  'setOpenAIKey' : ActorMethod<[string], undefined>,
  'storeTokens' : ActorMethod<[string, string, bigint], undefined>,
  'transformTokenResponse' : ActorMethod<[HttpTransformArgs], HttpResponse>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];