/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const TokenExchangeResult = IDL.Variant({
  'ok' : IDL.Text,
  'err' : IDL.Text,
});
export const CompletedLesson = IDL.Record({
  'lessonId' : IDL.Text,
  'completedAt' : IDL.Int,
});
export const Time = IDL.Int;
export const QA = IDL.Record({
  'at' : Time,
  'question' : IDL.Text,
  'response' : IDL.Text,
});
export const TokenStatus = IDL.Record({
  'isExpired' : IDL.Bool,
  'hasRefreshToken' : IDL.Bool,
  'hasToken' : IDL.Bool,
});
export const TweetResult = IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text });
export const HttpHeader = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
export const HttpResponse = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(HttpHeader),
});
export const HttpTransformArgs = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : HttpResponse,
});

export const idlService = IDL.Service({
  'askQuestion' : IDL.Func(
      [IDL.Opt(IDL.Text), IDL.Opt(IDL.Text), IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'disconnectX' : IDL.Func([], [], []),
  'exchangeToken' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [TokenExchangeResult],
      [],
    ),
  'getClientId' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
  'getOpenAIKey' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
  'getProgress' : IDL.Func([], [IDL.Vec(CompletedLesson)], ['query']),
  'getQAHistory' : IDL.Func([IDL.Opt(IDL.Text)], [IDL.Vec(QA)], ['query']),
  'getTokenStatus' : IDL.Func([], [TokenStatus], ['query']),
  'markComplete' : IDL.Func([IDL.Text], [], []),
  'postTweet' : IDL.Func([IDL.Text, IDL.Text], [TweetResult], []),
  'resetProgress' : IDL.Func([], [], []),
  'setClientId' : IDL.Func([IDL.Text], [], []),
  'setOpenAIKey' : IDL.Func([IDL.Text], [], []),
  'storeTokens' : IDL.Func([IDL.Text, IDL.Text, IDL.Int], [], []),
  'transformTokenResponse' : IDL.Func(
      [HttpTransformArgs],
      [HttpResponse],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const TokenExchangeResult = IDL.Variant({
    'ok' : IDL.Text,
    'err' : IDL.Text,
  });
  const CompletedLesson = IDL.Record({
    'lessonId' : IDL.Text,
    'completedAt' : IDL.Int,
  });
  const Time = IDL.Int;
  const QA = IDL.Record({
    'at' : Time,
    'question' : IDL.Text,
    'response' : IDL.Text,
  });
  const TokenStatus = IDL.Record({
    'isExpired' : IDL.Bool,
    'hasRefreshToken' : IDL.Bool,
    'hasToken' : IDL.Bool,
  });
  const TweetResult = IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text });
  const HttpHeader = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const HttpResponse = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(HttpHeader),
  });
  const HttpTransformArgs = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : HttpResponse,
  });
  
  return IDL.Service({
    'askQuestion' : IDL.Func(
        [IDL.Opt(IDL.Text), IDL.Opt(IDL.Text), IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'disconnectX' : IDL.Func([], [], []),
    'exchangeToken' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [TokenExchangeResult],
        [],
      ),
    'getClientId' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
    'getOpenAIKey' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
    'getProgress' : IDL.Func([], [IDL.Vec(CompletedLesson)], ['query']),
    'getQAHistory' : IDL.Func([IDL.Opt(IDL.Text)], [IDL.Vec(QA)], ['query']),
    'getTokenStatus' : IDL.Func([], [TokenStatus], ['query']),
    'markComplete' : IDL.Func([IDL.Text], [], []),
    'postTweet' : IDL.Func([IDL.Text, IDL.Text], [TweetResult], []),
    'resetProgress' : IDL.Func([], [], []),
    'setClientId' : IDL.Func([IDL.Text], [], []),
    'setOpenAIKey' : IDL.Func([IDL.Text], [], []),
    'storeTokens' : IDL.Func([IDL.Text, IDL.Text, IDL.Int], [], []),
    'transformTokenResponse' : IDL.Func(
        [HttpTransformArgs],
        [HttpResponse],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };