/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type TokenExchangeResult = {
    __kind__: "ok";
    ok: string;
} | {
    __kind__: "err";
    err: string;
};
export type TweetResult = {
    __kind__: "ok";
    ok: string;
} | {
    __kind__: "err";
    err: string;
};
export interface TokenStatus {
    isExpired: boolean;
    hasRefreshToken: boolean;
    hasToken: boolean;
}
export interface CompletedLesson {
    lessonId: string;
    completedAt: bigint;
}
export interface backendInterface {
    disconnectX(): Promise<void>;
    exchangeToken(code: string, codeVerifier: string, redirectUri: string): Promise<TokenExchangeResult>;
    /**
     * / Get the global X (Twitter) OAuth 2.0 Client ID.
     */
    getClientId(): Promise<string | null>;
    getProgress(): Promise<Array<CompletedLesson>>;
    getTokenStatus(): Promise<TokenStatus>;
    markComplete(lessonId: string): Promise<void>;
    postTweet(lessonId: string, lessonTitle: string): Promise<TweetResult>;
    resetProgress(): Promise<void>;
    /**
     * / Set the global X (Twitter) OAuth 2.0 Client ID.
     */
    setClientId(id: string): Promise<void>;
    storeTokens(accessToken: string, refreshToken: string, expiresAt: bigint): Promise<void>;
}
import type { TokenExchangeResult as _TokenExchangeResult, TweetResult as _TweetResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async disconnectX(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.disconnectX();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.disconnectX();
            return result;
        }
    }
    async exchangeToken(arg0: string, arg1: string, arg2: string): Promise<TokenExchangeResult> {
        if (this.processError) {
            try {
                const result = await this.actor.exchangeToken(arg0, arg1, arg2);
                return from_candid_TokenExchangeResult_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.exchangeToken(arg0, arg1, arg2);
            return from_candid_TokenExchangeResult_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getClientId(): Promise<string | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getClientId();
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getClientId();
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProgress(): Promise<Array<CompletedLesson>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProgress();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProgress();
            return result;
        }
    }
    async getTokenStatus(): Promise<TokenStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.getTokenStatus();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTokenStatus();
            return result;
        }
    }
    async markComplete(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markComplete(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markComplete(arg0);
            return result;
        }
    }
    async postTweet(arg0: string, arg1: string): Promise<TweetResult> {
        if (this.processError) {
            try {
                const result = await this.actor.postTweet(arg0, arg1);
                return from_candid_TweetResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.postTweet(arg0, arg1);
            return from_candid_TweetResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async resetProgress(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.resetProgress();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.resetProgress();
            return result;
        }
    }
    async setClientId(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setClientId(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setClientId(arg0);
            return result;
        }
    }
    async storeTokens(arg0: string, arg1: string, arg2: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.storeTokens(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.storeTokens(arg0, arg1, arg2);
            return result;
        }
    }
}
function from_candid_TokenExchangeResult_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TokenExchangeResult): TokenExchangeResult {
    return from_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function from_candid_TweetResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TweetResult): TweetResult {
    return from_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: string;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: string;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
